name: dev_env_switcher
description: A Flutter/Dart library to switch between development environments at runtime or build time.
version: 1.0.0
homepage: https://github.com/Deep3way/dev_env_switcher
repository: https://github.com/Deep3way/dev_env_switcher
issue_tracker: https://github.com/Deep3way/dev_env_switcher/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0  # For persistence

dev_dependencies:
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0